export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';

export const DISPLAY_POPULATION = 'DISPLAY_POPULATION';
export const SEARCH_POPULATION = 'SEARCH_POPULATION';
export const ON_POPULATION_CHANGE = 'ON_POPULATION_CHANGE';